### ISSUE TITLE
At the moment the steps are not applied

### ISSUE THREAD

**Issue by ghost** [Ibrahim-Mushtaha/Step_Counter_background_service#1]
Hello. The steps taken are not applied at the moment and need to close and re-size the application, if possible, fix this **bug**.

**Comment by MehdiSekoba** [comment]
> Hello. The steps taken are not applied at the moment and need to close and re-size the application, if possible, fix this **bug**.

**Comment by MehdiSekoba** [comment]
> Hello. The steps taken are not applied at the moment and need to close and re-size the application, if possible, fix this **bug**.

g
